name: cero
description: A finance app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  page_transition: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  toggle_switch: ^2.1.0
  auto_reload: ^1.1.0
  flutter_speed_dial: ^7.0.0
  flutter_phoenix: ^1.1.0
  eva_icons_flutter: ^3.1.0
  google_fonts: ^4.0.4
  unicons: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_iconpicker: ^3.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/CeroLogo.png"

flutter:
  assets:
    - lib/images/CeroLogo.png


  uses-material-design: true

 
  fonts:
     - family: Altone
       fonts:
         - asset: lib/fonts/AltoneRegular.ttf
           style: normal
         - asset: lib/fonts/AltoneBold.ttf
           weight: 700
         - asset: lib/fonts/AltoneItalic.ttf
           style: italic

     - family: TT Drugs Bold
       fonts:
         - asset: lib/fonts/TTDrugsBold.otf
           weight: 700

